// Generated by Wrangler on Tue Sep 10 2024 14:56:23 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	TELEGRAM_API_URL: "https://api.telegram.org/bot";
	SHEET_REFERENSI: "REFERENSI";
	SHEET_DATA: "DATA";
	BOT_TOKEN: string;
	DATABASE: D1Database;
}
